import { createContext, useContext, useState, ReactNode, useMemo, useCallback } from "react";

type Language = "en" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header
    "header.about": "About",
    "header.services": "Services",
    "header.pricing": "Pricing",
    "header.process": "Process",
    "header.faq": "FAQ",
    "header.schedule": "Schedule",
    "header.contact": "Contact",
    "header.getStarted": "Get Started",
    "header.brandName": "Canadian Tax Pro",
    "header.brandTagline": "Professional Tax Services",
    
    // Hero
    "hero.badge": "Trusted Canadian Tax Professional",
    "hero.title": "Complete Financial & Tax Solutions for Canadians",
    "hero.description": "Expert services in tax preparation, bookkeeping, and financial reporting for individuals, newcomers, and small businesses across Canada. Your partner in financial compliance and growth.",
    "hero.ctaPrimary": "Get Started Today",
    "hero.ctaSecondary": "View Services",
    "hero.expertiseLabel": "Expertise in",
    "hero.expertiseValue": "T1 Personal Returns",
    "hero.supportingLabel": "Supporting",
    "hero.supportingValue": "Small Businesses",
    
    // Hero Service Cards
    "hero.service1Title": "Personal Tax",
    "hero.service1Desc": "T1 returns for individuals & newcomers",
    "hero.service2Title": "Small Business",
    "hero.service2Desc": "Complete tax solutions for entrepreneurs",
    "hero.service3Title": "Bookkeeping",
    "hero.service3Desc": "Professional accounting services",
    "hero.service4Title": "Financial Reports",
    "hero.service4Desc": "Detailed analysis & insights",
    
    // About
    "about.section": "About Us",
    "about.title": "Your Trusted Partner in Canadian Tax Compliance",
    "about.p1": "As a dedicated Canadian tax professional, I specialize in helping individuals, newcomers, and small business owners navigate the complexities of the Canadian tax system with confidence.",
    "about.p2": "Whether you're filing your first T1 personal tax return in Canada, managing a small business, or seeking guidance on tax compliance, I provide personalized service that puts your needs first. My commitment is to ensure accuracy, maximize your eligible deductions, and keep you fully compliant with CRA requirements.",
    "about.value1Title": "Compliance & Accuracy",
    "about.value1Desc": "Ensuring full compliance with CRA regulations and accurate tax filings every time.",
    "about.value2Title": "Professional Excellence",
    "about.value2Desc": "Years of experience in Canadian tax law and dedication to staying current with regulations.",
    "about.value3Title": "Client-Focused Service",
    "about.value3Desc": "Personalized attention and support tailored to your unique tax situation.",
    "about.craCompliant": "CRA Compliant Services",
    "about.craCompliantDesc": "All services are designed to meet and exceed Canada Revenue Agency standards and requirements.",
    
    // Team
    "about.teamSection": "Who We Are",
    "about.teamTitle": "Meet Your Tax Professionals",
    "about.team1Name": "Veronica Prass",
    "about.team1Title": "Founder & Tax Professional",
    "about.team1Bio": "Specialized in personal and small business tax returns with a focus on helping newcomers navigate the Canadian tax system.",
    "about.team2Name": "Germana Azevedo",
    "about.team2Title": "Senior Tax Consultant",
    "about.team2Bio": "Expert in tax compliance and planning with extensive experience serving diverse Canadian clients.",
    "about.viewLinkedIn": "View LinkedIn Profile",
    
    // Services
    "services.section": "Services",
    "services.title": "Comprehensive Financial Services for Every Need",
    "services.description": "From personal tax returns to full bookkeeping and financial reporting, we offer complete solutions designed to meet your Canadian financial obligations with accuracy and efficiency.",
    
    // Main Service Areas
    "services.main1Title": "Personal Tax",
    "services.main1Desc": "Complete tax preparation and filing services for individuals and newcomers to Canada.",
    "services.main2Title": "Small Business",
    "services.main2Desc": "Comprehensive tax and compliance services for sole proprietors and small business owners.",
    "services.main3Title": "Bookkeeping",
    "services.main3Desc": "Professional bookkeeping and financial record management for your business.",
    "services.main4Title": "Financial Reports & Management",
    "services.main4Desc": "Management reports, financial analysis, and controller services for business insights.",
    
    // Personal Tax - Sub-services
    "services.personal1Title": "T1 Personal Tax Returns",
    "services.personal1Desc": "Complete preparation and filing of individual income tax returns.",
    "services.personal1Feature1": "Employment income (T4 slips)",
    "services.personal1Feature2": "Investment income and capital gains",
    "services.personal1Feature3": "RRSP contributions and deductions",
    "services.personal1Feature4": "Medical expenses and credits",
    
    "services.personal2Title": "Newcomer Tax Services",
    "services.personal2Desc": "Specialized support for new immigrants navigating Canadian taxes.",
    "services.personal2Feature1": "First-time tax filer assistance",
    "services.personal2Feature2": "Residency status determination",
    "services.personal2Feature3": "Foreign income reporting",
    "services.personal2Feature4": "Tax treaty benefits",
    
    "services.personal3Title": "Tax Compliance & Review",
    "services.personal3Desc": "Ensuring your tax filings meet all CRA requirements.",
    "services.personal3Feature1": "Prior year tax review",
    "services.personal3Feature2": "Notice of Assessment review",
    "services.personal3Feature3": "Missing slips and documentation",
    "services.personal3Feature4": "Amendment requests (T1-ADJ)",
    
    // Small Business - Sub-services
    "services.business1Title": "Business Tax Filings",
    "services.business1Desc": "Essential tax services for sole proprietors and small businesses.",
    "services.business1Feature1": "T2125 Statement of Business Activities",
    "services.business1Feature2": "Business expense optimization",
    "services.business1Feature3": "Home office deductions",
    "services.business1Feature4": "Quarterly tax planning",
    
    "services.business2Title": "GST/HST Returns",
    "services.business2Desc": "Complete GST/HST registration, filing, and compliance services.",
    "services.business2Feature1": "GST/HST registration",
    "services.business2Feature2": "Monthly/quarterly return preparation",
    "services.business2Feature3": "Input tax credit optimization",
    "services.business2Feature4": "GST/HST compliance review",
    
    "services.business3Title": "Business Planning",
    "services.business3Desc": "Strategic business and tax planning for growth.",
    "services.business3Feature1": "Business structure consultation",
    "services.business3Feature2": "Tax-efficient compensation planning",
    "services.business3Feature3": "Incorporation advice",
    "services.business3Feature4": "Growth strategy tax planning",
    
    // Bookkeeping - Sub-services
    "services.bookkeeping1Title": "Monthly Bookkeeping",
    "services.bookkeeping1Desc": "Professional monthly bookkeeping and reconciliation services.",
    "services.bookkeeping1Feature1": "Bank reconciliation",
    "services.bookkeeping1Feature2": "Accounts payable/receivable",
    "services.bookkeeping1Feature3": "Financial statements preparation",
    "services.bookkeeping1Feature4": "Monthly financial reports",
    
    "services.bookkeeping2Title": "Expense Tracking",
    "services.bookkeeping2Desc": "Comprehensive expense categorization and tracking.",
    "services.bookkeeping2Feature1": "Receipt management",
    "services.bookkeeping2Feature2": "Expense categorization",
    "services.bookkeeping2Feature3": "Vendor payment tracking",
    "services.bookkeeping2Feature4": "Tax-deductible expense identification",
    
    "services.bookkeeping3Title": "Financial Records",
    "services.bookkeeping3Desc": "Complete financial record organization and management.",
    "services.bookkeeping3Feature1": "Document organization",
    "services.bookkeeping3Feature2": "Digital record keeping",
    "services.bookkeeping3Feature3": "Audit-ready documentation",
    "services.bookkeeping3Feature4": "Year-end preparation",
    
    // Financial Reports - Sub-services
    "services.reports1Title": "Management Reports",
    "services.reports1Desc": "Comprehensive management reports for informed decision-making.",
    "services.reports1Feature1": "Profit & Loss statements",
    "services.reports1Feature2": "Cash flow reports",
    "services.reports1Feature3": "Budget vs Actual analysis",
    "services.reports1Feature4": "Custom management dashboards",
    
    "services.reports2Title": "Financial Analysis",
    "services.reports2Desc": "In-depth financial analysis to drive business performance.",
    "services.reports2Feature1": "Financial ratio analysis",
    "services.reports2Feature2": "Profitability analysis",
    "services.reports2Feature3": "Cost structure analysis",
    "services.reports2Feature4": "Trend and variance analysis",
    
    "services.reports3Title": "Controller Services",
    "services.reports3Desc": "Strategic controller services for financial oversight and planning.",
    "services.reports3Feature1": "KPI tracking and reporting",
    "services.reports3Feature2": "Performance metrics",
    "services.reports3Feature3": "Financial planning & forecasting",
    "services.reports3Feature4": "Strategic business insights",
    
    "services.notSureTitle": "Not Sure Which Service You Need?",
    "services.notSureDesc": "Contact us for a free consultation to discuss your specific financial and tax situation.",
    
    // Process
    "process.section": "How It Works",
    "process.title": "A Simple, Transparent Process",
    "process.description": "From initial consultation to final filing, every step is designed to be clear, efficient, and stress-free.",
    "process.tabPersonal": "Personal Tax",
    "process.tabBusiness": "Business Services",
    
    // Personal Tax Process
    "process.step1Title": "Initial Payment ($50)",
    "process.step1Desc": "Pay a small deposit of $50 CAD to start your tax filing. The remaining balance is due after we complete your return.",
    "process.step1Time": "2 minutes",
    "process.step2Title": "Document Upload",
    "process.step2Desc": "Upload your tax documents (T4s, receipts, slips, etc.) through our secure portal with automatic OCR extraction.",
    "process.step2Time": "15-30 minutes",
    "process.step3Title": "Tax Calculation & Review",
    "process.step3Desc": "We analyze your documents, calculate your refund/owing, and prepare your complete tax return.",
    "process.step3Time": "3-5 business days",
    "process.step4Title": "Final Payment & Approval",
    "process.step4Desc": "Review your completed return, pay the remaining balance, and approve for CRA submission.",
    "process.step4Time": "30 minutes",
    "process.step5Title": "Filed with CRA",
    "process.step5Desc": "Your tax return is electronically filed with the CRA. You'll receive your refund in 2-3 weeks!",
    "process.step5Time": "Same day",
    
    // Business Services Process
    "process.business1Title": "Free Initial Consultation",
    "process.business1Desc": "Schedule a complimentary consultation to discuss your business needs and scope of work.",
    "process.business1Time": "30-45 minutes",
    "process.business2Title": "Proposal & Scope Review",
    "process.business2Desc": "Receive a detailed proposal with pricing, timeline, and customized service plan.",
    "process.business2Time": "1-2 days",
    "process.business3Title": "Onboarding & Setup",
    "process.business3Desc": "Complete onboarding, documentation, and initial setup of your business accounts.",
    "process.business3Time": "3-5 days",
    "process.business4Title": "Ongoing Service Delivery",
    "process.business4Desc": "Regular service delivery with monthly reports, continuous support, and strategic guidance.",
    "process.business4Time": "Ongoing",
    
    "process.businessBannerTitle": "🎉 First Consultation is FREE!",
    "process.businessBannerDesc": "For Small Business, Bookkeeping, and Financial Reports services, we start with a complimentary consultation to understand your needs and provide a customized proposal.",
    "process.businessBannerButton": "Schedule Free Consultation",
    
    "process.turnaroundTitle": "Average Turnaround Time: 5-7 Business Days",
    "process.turnaroundDesc": "From document submission to final filing. Rush service available for urgent situations.",
    "process.benefit1": "Free initial consultation",
    "process.benefit2": "Secure document handling",
    "process.benefit3": "Electronic CRA filing",
    
    // FAQ
    "faq.section": "Frequently Asked Questions",
    "faq.title": "Common Questions About Canadian Tax Services",
    "faq.description": "Find answers to the most common questions about tax filing, compliance, and working with a tax professional in Canada.",
    "faq.stillHaveTitle": "Still Have Questions?",
    "faq.stillHaveDesc": "Don't hesitate to reach out. I'm here to help clarify any aspect of your Canadian tax obligations.",
    "faq.contactLink": "Contact me today",
    
    // Contact
    "contact.section": "Get In Touch",
    "contact.title": "Ready to Get Started?",
    "contact.description": "Contact me today for a free consultation. I'm here to answer your questions and help you navigate your Canadian tax obligations with confidence.",
    "contact.infoTitle": "Contact Information",
    "contact.locationLabel": "Location",
    "contact.hoursLabel": "Hours",
    "contact.locationValue": "Serving clients across Canada",
    "contact.hoursValue": "Mon-Fri: 9am-6pm EST",
    "contact.taxSeasonTitle": "Tax Season Hours",
    "contact.taxSeasonDesc": "During tax season (February - April), extended hours are available including evenings and weekends by appointment.",
    "contact.virtualDesc": "Virtual consultations available for clients across all Canadian provinces and territories.",
    "contact.formTitle": "Send Me a Message",
    "contact.nameLabel": "Full Name",
    "contact.emailLabel": "Email Address",
    "contact.phoneLabel": "Phone Number",
    "contact.subjectLabel": "Subject",
    "contact.messageLabel": "Message",
    "contact.namePlaceholder": "John Smith",
    "contact.emailPlaceholder": "john@example.com",
    "contact.phonePlaceholder": "(555) 123-4567",
    "contact.subjectPlaceholder": "T1 Personal Tax Return",
    "contact.messagePlaceholder": "Please describe your tax situation and how I can help you...",
    "contact.privacyTitle": "Privacy Notice:",
    "contact.privacyText": "Your information is kept strictly confidential and will only be used to respond to your inquiry.",
    "contact.consentText": "By submitting this form, you agree to be contacted regarding your tax service inquiry.",
    "contact.submitButton": "Send Message",
    "contact.scheduleTitle": "Schedule a Free Consultation",
    "contact.scheduleDesc": "Book a convenient time to discuss your tax and financial needs.",
    
    // Scheduling
    "scheduling.section": "Book Appointment",
    "scheduling.title": "Schedule Your Free Consultation",
    "scheduling.description": "Select a date and time that works best for you. I'll confirm your appointment within 24 hours.",
    "scheduling.selectDate": "Select a Date",
    "scheduling.selectTime": "Select a Time",
    "scheduling.noTimesAvailable": "No times available for this date",
    "scheduling.bookingDetails": "Booking Details",
    "scheduling.selectedDate": "Selected Date",
    "scheduling.selectedTime": "Selected Time",
    "scheduling.fullName": "Full Name",
    "scheduling.email": "Email Address",
    "scheduling.phone": "Phone Number",
    "scheduling.serviceType": "Service Type",
    "scheduling.selectService": "Select a service",
    "scheduling.servicePersonal": "T1 Personal Tax Return",
    "scheduling.serviceNewcomer": "Newcomer Tax Services",
    "scheduling.serviceSmallBusiness": "Small Business Filing",
    "scheduling.serviceCompliance": "Tax Compliance & Review",
    "scheduling.servicePlanning": "Tax Planning & Advice",
    "scheduling.serviceRepresentation": "CRA Representation",
    "scheduling.additionalNotes": "Additional Notes (Optional)",
    "scheduling.notesPlaceholder": "Please share any specific questions or concerns...",
    "scheduling.confirmBooking": "Confirm Booking",
    "scheduling.morning": "Morning",
    "scheduling.afternoon": "Afternoon",
    "scheduling.evening": "Evening",
    "scheduling.virtualMeeting": "This will be a virtual consultation via video call.",
    "scheduling.bookingSuccess": "Booking request submitted! You'll receive a confirmation email shortly.",
    
    // Client Portal
    "clientPortal.title": "Client Portal",
    "clientPortal.subtitle": "Manage your tax documents securely",
    "clientPortal.login": "Client Login",
    "clientPortal.signup": "Create Account",
    "clientPortal.email": "Email",
    "clientPortal.password": "Password",
    "clientPortal.name": "Full Name",
    "clientPortal.signInButton": "Sign In",
    "clientPortal.signUpButton": "Create Account",
    "clientPortal.alreadyHaveAccount": "Already have an account?",
    "clientPortal.noAccount": "Don't have an account?",
    "clientPortal.signInHere": "Sign in here",
    "clientPortal.signUpHere": "Sign up here",
    "clientPortal.welcomeBack": "Welcome back",
    "clientPortal.logout": "Logout",
    "clientPortal.uploadDocuments": "Upload Documents",
    "clientPortal.myDocuments": "My Documents",
    "clientPortal.noDocuments": "No documents uploaded yet",
    "clientPortal.uploadNew": "Upload New Document",
    "clientPortal.selectCategory": "Select Document Category",
    "clientPortal.description": "Description (optional)",
    "clientPortal.chooseFile": "Choose File",
    "clientPortal.uploadButton": "Upload Document",
    "clientPortal.uploading": "Uploading...",
    "clientPortal.cancel": "Cancel",
    "clientPortal.delete": "Delete",
    "clientPortal.uploadedOn": "Uploaded on",
    "clientPortal.fileSize": "Size",
    "clientPortal.category": "Category",
    "clientPortal.forgotPassword": "Forgot password?",
    
    // Forgot Password
    "forgotPassword.title": "Reset Password",
    "forgotPassword.subtitle": "Enter your email and we'll send you a link to reset your password",
    "forgotPassword.emailHint": "We'll send a password reset link to this email address",
    "forgotPassword.sendButton": "Send Reset Link",
    "forgotPassword.successTitle": "Check Your Email",
    "forgotPassword.successMessage": "We've sent a password reset link to your email address. Click the link in the email to reset your password.",
    "forgotPassword.checkSpam": "If you don't see the email, check your spam folder.",
    "forgotPassword.backToLogin": "Back to login",
    
    // Reset Password
    "resetPassword.title": "Create New Password",
    "resetPassword.subtitle": "Enter your new password below",
    "resetPassword.newPassword": "New Password",
    "resetPassword.confirmPassword": "Confirm Password",
    "resetPassword.passwordHint": "Must be at least 6 characters",
    "resetPassword.updateButton": "Update Password",
    
    // Document Categories
    "docCategory.t4": "T4 - Employment Income",
    "docCategory.t4e": "T4E - Employment Insurance",
    "docCategory.t4a": "T4A - Pension, Retirement, Scholarships",
    "docCategory.t5": "T5 - Investment Income",
    "docCategory.t5008": "T5008 - Securities Transactions",
    "docCategory.rl1": "RL-1 - Quebec Employment Income",
    "docCategory.rl2": "RL-2 - Quebec Retirement Income",
    "docCategory.rental": "Rental Income",
    "docCategory.selfEmployed": "Self-Employment / Freelance",
    "docCategory.foreign": "Foreign Income",
    "docCategory.medical": "Medical Expenses",
    "docCategory.education": "Education (T2202/RL-8)",
    "docCategory.homeOffice": "Home Office Expenses (T2200)",
    "docCategory.rrsp": "RRSP Contributions",
    "docCategory.charity": "Charitable Donations",
    "docCategory.childcare": "Childcare Expenses",
    "docCategory.property": "Property Tax",
    "docCategory.other": "Other Documents",

    // Messages
    "messages.title": "Messages",
    "messages.noMessages": "No messages yet",
    "messages.writeMessage": "Write a message...",
    "messages.send": "Send",
    "messages.you": "You",
    "messages.admin": "Tax Advisor",
    "messages.today": "Today",
    "messages.yesterday": "Yesterday",
    "messages.sending": "Sending...",
    "messages.loadMore": "Load more messages",

    // Onboarding
    "onboarding.title": "Complete Your Profile",
    "onboarding.subtitle": "Let's get your account set up",
    "onboarding.step": "Step",
    "onboarding.of": "of",
    "onboarding.step1Title": "Basic Information",
    "onboarding.step1Desc": "Tell us about yourself",
    "onboarding.step2Title": "Service Type",
    "onboarding.step2Desc": "What service do you need?",
    "onboarding.step3Title": "Tax Return Details",
    "onboarding.step3Desc": "Additional information for your tax return",
    "onboarding.fullName": "Full Name",
    "onboarding.fullNamePlaceholder": "John Doe",
    "onboarding.phone": "Phone Number",
    "onboarding.email": "Email",
    "onboarding.address": "Street Address",
    "onboarding.addressPlaceholder": "123 Main Street",
    "onboarding.city": "City",
    "onboarding.cityPlaceholder": "Toronto",
    "onboarding.province": "Province",
    "onboarding.selectProvince": "Select province",
    "onboarding.postalCode": "Postal Code",
    "onboarding.serviceCategory": "Which service do you need?",
    "onboarding.personal": "Personal Tax",
    "onboarding.personalDesc": "T1 personal tax returns for individuals and newcomers",
    "onboarding.smallBusiness": "Small Business",
    "onboarding.smallBusinessDesc": "Business tax filings, GST/HST returns, and planning",
    "onboarding.bookkeeping": "Bookkeeping",
    "onboarding.bookkeepingDesc": "Monthly bookkeeping, expense tracking, and financial records",
    "onboarding.financialReports": "Financial Reports & Management",
    "onboarding.financialReportsDesc": "Management reports, financial analysis, and controller services",
    "onboarding.personalInfo": "Personal Information",
    "onboarding.dateOfBirth": "Date of Birth",
    "onboarding.sin": "Social Insurance Number (SIN)",
    "onboarding.statusInfo": "Status Information",
    "onboarding.maritalStatus": "Marital Status",
    "onboarding.selectMaritalStatus": "Select status",
    "onboarding.single": "Single",
    "onboarding.married": "Married",
    "onboarding.commonLaw": "Common-law",
    "onboarding.divorced": "Divorced",
    "onboarding.widowed": "Widowed",
    "onboarding.numberOfDependents": "Number of Dependents",
    "onboarding.firstTimeInCanada": "First time filing in Canada?",
    "onboarding.selectYesNo": "Select yes or no",
    "onboarding.yes": "Yes",
    "onboarding.no": "No",
    "onboarding.residencyStatus": "Residency Status",
    "onboarding.selectResidencyStatus": "Select status",
    "onboarding.resident": "Resident",
    "onboarding.nonResident": "Non-resident",
    "onboarding.deemedResident": "Deemed Resident",
    "onboarding.incomeInfo": "Employment & Income",
    "onboarding.incomeType": "Income Type",
    "onboarding.selectIncomeType": "Select type",
    "onboarding.employment": "Employment",
    "onboarding.selfEmployed": "Self-Employed",
    "onboarding.both": "Both",
    "onboarding.other": "Other",
    "onboarding.workProvince": "Work Province",
    "onboarding.back": "Back",
    "onboarding.continue": "Continue",
    "onboarding.complete": "Complete Setup",
    "onboarding.saving": "Saving...",
    "onboarding.saveProgress": "Save Progress & Continue Later",
    "onboarding.fillAllFields": "Please fill in all required fields",
    "onboarding.selectServiceCategory": "Please select a service category",
    "onboarding.profileCompleted": "Profile completed! Welcome to your dashboard.",
    "onboarding.progressSaved": "Progress saved successfully",
    "onboarding.saveFailed": "Failed to save profile",
    
    // Onboarding Success
    "onboardingSuccess.title": "Registration Complete!",
    "onboardingSuccess.subtitle": "Your profile has been successfully set up.",
    "onboardingSuccess.description": "You now have access to your client portal.",
    "onboardingSuccess.nextSteps": "You can now upload documents, track your service progress, and communicate with us directly through your portal.",
    "onboardingSuccess.accessPortal": "Access Client Portal",
    "onboardingSuccess.contact": "Need help? Contact us anytime.",
    
    // Footer
    "footer.description": "Expert Canadian tax services for individuals, newcomers, and small businesses. Ensuring compliance and maximizing your returns.",
    "footer.quickLinks": "Quick Links",
    "footer.services": "Services",
    "footer.contact": "Contact",
    "footer.service1": "T1 Personal Returns",
    "footer.service2": "Newcomer Services",
    "footer.service3": "Small Business Filing",
    "footer.service4": "Tax Compliance",
    "footer.service5": "CRA Representation",
    "footer.copyright": "Canadian Tax Pro. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.disclaimer": "This website is for informational purposes. Tax advice is provided on a case-by-case basis during consultations. All services comply with Canada Revenue Agency regulations.",
    
    // Admin Panel
    "admin.panel": "Admin Panel",
    "admin.welcomeBack": "Welcome back",
    "admin.clientPortal": "Client Portal",
    "admin.signOut": "Sign Out",
    "admin.adminHub": "Admin Hub",
    "admin.selectModule": "Select a module below to get started",
    
    // Admin Modules
    "admin.clientsTitle": "Customer Dashboard",
    "admin.clientsDesc": "Manage all customers, view details, documents, and filing status",
    "admin.bookkeepingTitle": "Bookkeeping Dashboard",
    "admin.bookkeepingDesc": "Track expenses, manage invoices, and handle day-to-day accounting",
    "admin.financialTitle": "Financial Dashboard",
    "admin.financialDesc": "View KPIs, revenue analytics, and comprehensive financial reports",
    "admin.generalDashboardTitle": "General Dashboard",
    "admin.generalDashboardDesc": "Overview of all system operations and quick access to key functions",
    "admin.marketingTitle": "Marketing Dashboard",
    "admin.marketingDesc": "Create professional marketing images and manage campaigns",
    
    // Customer Dashboard
    "admin.customerDashboard": "Customer Dashboard",
    "admin.customersTotal": "customers total",
    "admin.customer": "customer",
    "admin.customers": "customers",
    "admin.viewProfile": "View Profile",
    "admin.pending": "Pending",
    "admin.active": "Active",
    "admin.completed": "Completed",
    "admin.searchCustomers": "Search customers...",
    "admin.filterAll": "All",
    "admin.filterPersonal": "Personal Tax",
    "admin.filterBusiness": "Small Business",
    "admin.filterBookkeeping": "Bookkeeping",
    "admin.filterReports": "Financial Reports",
    "admin.noCustomers": "No customers found",
    "admin.backToHub": "Back to Hub",
    
    // Tax Filing Detail Page
    "taxFiling.overview": "Overview",
    "taxFiling.documents": "Documents",
    "taxFiling.messages": "Messages",
    "taxFiling.taxYear": "Tax Year",
    "taxFiling.filingType": "Filing Type",
    "taxFiling.status": "Status",
    "taxFiling.created": "Created",
    "taxFiling.lastUpdated": "Last Updated",
    "taxFiling.statusPending": "Pending Payment",
    "taxFiling.statusDocuments": "Documents Upload",
    "taxFiling.statusReview": "Under Review",
    "taxFiling.statusReady": "Ready for Payment",
    "taxFiling.statusCompleted": "Completed",
    "taxFiling.paymentTimeline": "Payment Timeline",
    "taxFiling.step1": "Initial Payment",
    "taxFiling.step1Desc": "Pay $50 CAD deposit to start",
    "taxFiling.step2": "Upload Documents",
    "taxFiling.step2Desc": "Upload your tax documents",
    "taxFiling.step3": "We Prepare",
    "taxFiling.step3Desc": "We calculate and prepare your return",
    "taxFiling.step4": "Final Payment",
    "taxFiling.step4Desc": "Pay remaining balance",
    "taxFiling.step5": "Filed",
    "taxFiling.step5Desc": "Submitted to CRA",
    "taxFiling.payInitial": "Pay $50 Initial Deposit",
    "taxFiling.uploadDocuments": "Upload Documents",
    "taxFiling.viewReport": "View Tax Report",
    "taxFiling.payFinal": "Pay Final Balance",
    "taxFiling.downloadReceipt": "Download Receipt",
    "taxFiling.initialPaymentPaid": "Initial Payment Paid",
    "taxFiling.finalPaymentPaid": "Final Payment Paid",
    "taxFiling.paidOn": "Paid on",
    "taxFiling.amount": "Amount",
    "taxFiling.refundAmount": "Estimated Refund",
    "taxFiling.owingAmount": "Amount Owing to CRA",
    "taxFiling.finalPrice": "Final Service Price",
    "taxFiling.backToDashboard": "Back to Dashboard"
  },
  fr: {
    // Header
    "header.about": "À propos",
    "header.services": "Services",
    "header.pricing": "Tarifs",
    "header.process": "Processus",
    "header.faq": "FAQ",
    "header.schedule": "Programme",
    "header.contact": "Contact",
    "header.getStarted": "Commencer",
    "header.brandName": "Fiscaliste Canadien",
    "header.brandTagline": "Services Fiscaux Professionnels",
    
    // Hero
    "hero.badge": "Fiscaliste Canadien de Confiance",
    "hero.title": "Solutions Financières et Fiscales Complètes pour les Canadiens",
    "hero.description": "Services experts en préparation fiscale, comptabilité et rapports financiers pour particuliers, nouveaux arrivants et petites entreprises partout au Canada. Votre partenaire en conformité financière et croissance.",
    "hero.ctaPrimary": "Commencer Aujourd'hui",
    "hero.ctaSecondary": "Voir les Services",
    "hero.expertiseLabel": "Expertise en",
    "hero.expertiseValue": "Déclarations T1 Personnelles",
    "hero.supportingLabel": "Soutien aux",
    "hero.supportingValue": "Petites Entreprises",
    
    // Hero Service Cards
    "hero.service1Title": "Impôt Personnel",
    "hero.service1Desc": "Déclarations T1 pour particuliers et nouveaux arrivants",
    "hero.service2Title": "Petite Entreprise",
    "hero.service2Desc": "Solutions fiscales complètes pour entrepreneurs",
    "hero.service3Title": "Comptabilité",
    "hero.service3Desc": "Services comptables professionnels",
    "hero.service4Title": "Rapports Financiers",
    "hero.service4Desc": "Analyse et perspectives détaillées",
    
    // About
    "about.section": "À Propos",
    "about.title": "Votre Partenaire de Confiance en Conformité Fiscale Canadienne",
    "about.p1": "En tant que fiscaliste canadien dévoué, je me spécialise dans l'aide aux particuliers, nouveaux arrivants et propriétaires de petites entreprises pour naviguer les complexités du système fiscal canadien avec confiance.",
    "about.p2": "Que vous produisiez votre première déclaration T1 au Canada, que vous gériez une petite entreprise ou que vous cherchiez des conseils sur la conformité fiscale, je fournis un service personnalisé qui place vos besoins en premier. Mon engagement est d'assurer l'exactitude, de maximiser vos déductions admissibles et de vous maintenir en pleine conformité avec les exigences de l'ARC.",
    "about.value1Title": "Conformité et Précision",
    "about.value1Desc": "Assurer la pleine conformité aux réglementations de l'ARC et des déclarations fiscales exactes à chaque fois.",
    "about.value2Title": "Excellence Professionnelle",
    "about.value2Desc": "Des années d'expérience en droit fiscal canadien et un engagement à rester à jour avec les réglementations.",
    "about.value3Title": "Service Centré sur le Client",
    "about.value3Desc": "Attention personnalisée et soutien adapté à votre situation fiscale unique.",
    "about.craCompliant": "Services Conformes à l'ARC",
    "about.craCompliantDesc": "Tous les services sont conçus pour respecter et dépasser les normes et exigences de l'Agence du revenu du Canada.",
    
    // Team
    "about.teamSection": "Qui Sommes-Nous",
    "about.teamTitle": "Rencontrez Vos Fiscalistes",
    "about.team1Name": "Veronica Prass",
    "about.team1Title": "Fondatrice et Fiscaliste",
    "about.team1Bio": "Spécialisée dans les déclarations fiscales personnelles et de petites entreprises, avec un accent sur l'aide aux nouveaux arrivants pour naviguer le système fiscal canadien.",
    "about.team2Name": "Germana Azevedo",
    "about.team2Title": "Consultante Fiscale Senior",
    "about.team2Bio": "Experte en conformité et planification fiscale avec une vaste expérience au service de clients canadiens diversifiés.",
    "about.viewLinkedIn": "Voir le Profil LinkedIn",
    
    // Services
    "services.section": "Services",
    "services.title": "Services Financiers Complets pour Tous les Besoins",
    "services.description": "Des déclarations fiscales personnelles à la comptabilité complète et aux rapports financiers, nous offrons des solutions complètes conçues pour répondre à vos obligations financières canadiennes avec précision et efficacité.",
    
    // Main Service Areas
    "services.main1Title": "Impôt Personnel",
    "services.main1Desc": "Services complets de préparation et de production de déclarations fiscales pour particuliers et nouveaux arrivants au Canada.",
    "services.main2Title": "Petite Entreprise",
    "services.main2Desc": "Services fiscaux et de conformité complets pour travailleurs autonomes et propriétaires de petites entreprises.",
    "services.main3Title": "Comptabilité",
    "services.main3Desc": "Comptabilité professionnelle et gestion des dossiers financiers pour votre entreprise.",
    "services.main4Title": "Rapports Financiers et Gestion",
    "services.main4Desc": "Rapports de gestion, analyse financière et services de contrôleur pour des perspectives commerciales.",
    
    // Personal Tax - Sub-services
    "services.personal1Title": "Déclarations T1 d'Impôt Personnel",
    "services.personal1Desc": "Préparation et production complètes de déclarations de revenus des particuliers.",
    "services.personal1Feature1": "Revenu d'emploi (feuillets T4)",
    "services.personal1Feature2": "Revenu de placements et gains en capital",
    "services.personal1Feature3": "Cotisations REER et déductions",
    "services.personal1Feature4": "Frais médicaux et crédits",
    
    "services.personal2Title": "Services Fiscaux pour Nouveaux Arrivants",
    "services.personal2Desc": "Soutien spécialisé pour les nouveaux immigrants qui naviguent les impôts canadiens.",
    "services.personal2Feature1": "Aide pour les premiers déclarants",
    "services.personal2Feature2": "Détermination du statut de résidence",
    "services.personal2Feature3": "Déclaration de revenus étrangers",
    "services.personal2Feature4": "Avantages des conventions fiscales",
    
    "services.personal3Title": "Conformité et Révision Fiscale",
    "services.personal3Desc": "S'assurer que vos déclarations fiscales répondent à toutes les exigences de l'ARC.",
    "services.personal3Feature1": "Révision des années antérieures",
    "services.personal3Feature2": "Révision de l'avis de cotisation",
    "services.personal3Feature3": "Feuillets et documentation manquants",
    "services.personal3Feature4": "Demandes de modification (T1-ADJ)",
    
    // Small Business - Sub-services
    "services.business1Title": "Déclarations Fiscales d'Entreprise",
    "services.business1Desc": "Services fiscaux essentiels pour travailleurs autonomes et petites entreprises.",
    "services.business1Feature1": "T2125 État des activités d'une entreprise",
    "services.business1Feature2": "Optimisation des dépenses d'entreprise",
    "services.business1Feature3": "Déductions pour bureau à domicile",
    "services.business1Feature4": "Planification fiscale trimestrielle",
    
    "services.business2Title": "Déclarations TPS/TVH",
    "services.business2Desc": "Services complets d'inscription, de production et de conformité TPS/TVH.",
    "services.business2Feature1": "Inscription TPS/TVH",
    "services.business2Feature2": "Préparation de déclarations mensuelles/trimestrielles",
    "services.business2Feature3": "Optimisation des crédits de taxe sur intrants",
    "services.business2Feature4": "Révision de conformité TPS/TVH",
    
    "services.business3Title": "Planification d'Entreprise",
    "services.business3Desc": "Planification stratégique d'entreprise et fiscale pour la croissance.",
    "services.business3Feature1": "Consultation sur la structure d'entreprise",
    "services.business3Feature2": "Planification de rémunération fiscalement avantageuse",
    "services.business3Feature3": "Conseils sur l'incorporation",
    "services.business3Feature4": "Planification fiscale de stratégie de croissance",
    
    // Bookkeeping - Sub-services
    "services.bookkeeping1Title": "Comptabilité Mensuelle",
    "services.bookkeeping1Desc": "Services professionnels de comptabilité et de rapprochement mensuels.",
    "services.bookkeeping1Feature1": "Rapprochement bancaire",
    "services.bookkeeping1Feature2": "Comptes créditeurs/débiteurs",
    "services.bookkeeping1Feature3": "Préparation d'états financiers",
    "services.bookkeeping1Feature4": "Rapports financiers mensuels",
    
    "services.bookkeeping2Title": "Suivi des Dépenses",
    "services.bookkeeping2Desc": "Catégorisation et suivi complets des dépenses.",
    "services.bookkeeping2Feature1": "Gestion des reçus",
    "services.bookkeeping2Feature2": "Catégorisation des dépenses",
    "services.bookkeeping2Feature3": "Suivi des paiements aux fournisseurs",
    "services.bookkeeping2Feature4": "Identification des dépenses déductibles d'impôt",
    
    "services.bookkeeping3Title": "Dossiers Financiers",
    "services.bookkeeping3Desc": "Organisation et gestion complètes des dossiers financiers.",
    "services.bookkeeping3Feature1": "Organisation de documents",
    "services.bookkeeping3Feature2": "Tenue de dossiers numériques",
    "services.bookkeeping3Feature3": "Documentation prête pour audit",
    "services.bookkeeping3Feature4": "Préparation de fin d'année",
    
    // Financial Reports - Sub-services
    "services.reports1Title": "Rapports de Gestion",
    "services.reports1Desc": "Rapports de gestion complets pour une prise de décision éclairée.",
    "services.reports1Feature1": "États des profits et pertes",
    "services.reports1Feature2": "Rapports de flux de trésorerie",
    "services.reports1Feature3": "Analyse budget vs réel",
    "services.reports1Feature4": "Tableaux de bord de gestion personnalisés",
    
    "services.reports2Title": "Analyse Financière",
    "services.reports2Desc": "Analyse financière approfondie pour stimuler la performance de l'entreprise.",
    "services.reports2Feature1": "Analyse des ratios financiers",
    "services.reports2Feature2": "Analyse de rentabilité",
    "services.reports2Feature3": "Analyse de structure de coûts",
    "services.reports2Feature4": "Analyse des tendances et écarts",
    
    "services.reports3Title": "Services de Contrôleur",
    "services.reports3Desc": "Services stratégiques de contrôleur pour la surveillance et la planification financières.",
    "services.reports3Feature1": "Suivi et rapports des KPI",
    "services.reports3Feature2": "Métriques de performance",
    "services.reports3Feature3": "Planification et prévisions financières",
    "services.reports3Feature4": "Perspectives commerciales stratégiques",
    
    "services.notSureTitle": "Pas Sûr du Service Dont Vous Avez Besoin?",
    "services.notSureDesc": "Contactez-nous pour une consultation gratuite afin de discuter de votre situation financière et fiscale spécifique.",
    
    // Process
    "process.section": "Comment Ça Marche",
    "process.title": "Un Processus Simple et Transparent",
    "process.description": "De la consultation initiale au dépôt final, chaque étape est conçue pour être claire, efficace et sans stress.",
    "process.tabPersonal": "Impôt Personnel",
    "process.tabBusiness": "Services Entreprise",
    
    // Personal Tax Process
    "process.step1Title": "Paiement Initial (50$)",
    "process.step1Desc": "Payez un petit dépôt de 50$ CAD pour commencer votre déclaration. Le solde restant est dû après avoir terminé.",
    "process.step1Time": "2 minutes",
    "process.step2Title": "Téléchargement de Documents",
    "process.step2Desc": "Téléchargez vos documents fiscaux (T4, reçus, feuillets, etc.) via notre portail sécurisé avec extraction OCR automatique.",
    "process.step2Time": "15-30 minutes",
    "process.step3Title": "Calcul et Révision Fiscale",
    "process.step3Desc": "Nous analysons vos documents, calculons votre remboursement/montant dû et préparons votre déclaration complète.",
    "process.step3Time": "3-5 jours ouvrables",
    "process.step4Title": "Paiement Final et Approbation",
    "process.step4Desc": "Révisez votre déclaration terminée, payez le solde restant et approuvez pour soumission à l'ARC.",
    "process.step4Time": "30 minutes",
    "process.step5Title": "Déposé à l'ARC",
    "process.step5Desc": "Votre déclaration est déposée électroniquement à l'ARC. Vous recevrez votre remboursement dans 2-3 semaines!",
    "process.step5Time": "Jour même",
    
    // Business Services Process
    "process.business1Title": "Consultation Initiale Gratuite",
    "process.business1Desc": "Planifiez une consultation gratuite pour discuter de vos besoins d'entreprise et de la portée des travaux.",
    "process.business1Time": "30-45 minutes",
    "process.business2Title": "Proposition et Révision de la Portée",
    "process.business2Desc": "Recevez une proposition détaillée avec tarification, calendrier et plan de service personnalisé.",
    "process.business2Time": "1-2 jours",
    "process.business3Title": "Intégration et Configuration",
    "process.business3Desc": "Complétez l'intégration, la documentation et la configuration initiale de vos comptes d'entreprise.",
    "process.business3Time": "3-5 jours",
    "process.business4Title": "Prestation de Services Continue",
    "process.business4Desc": "Prestation régulière de services avec rapports mensuels, soutien continu et conseils stratégiques.",
    "process.business4Time": "Continu",
    
    "process.businessBannerTitle": "🎉 Première Consultation GRATUITE!",
    "process.businessBannerDesc": "Pour les services de Petites Entreprises, Comptabilité et Rapports Financiers, nous commençons par une consultation gratuite pour comprendre vos besoins et fournir une proposition personnalisée.",
    "process.businessBannerButton": "Planifier une Consultation Gratuite",
    
    "process.turnaroundTitle": "Temps de Traitement Moyen: 5-7 Jours Ouvrables",
    "process.turnaroundDesc": "De la soumission des documents au dépôt final. Service accéléré disponible pour les situations urgentes.",
    "process.benefit1": "Consultation initiale gratuite",
    "process.benefit2": "Traitement sécurisé des documents",
    "process.benefit3": "Dépôt électronique à l'ARC",
    
    // FAQ
    "faq.section": "Questions Fréquemment Posées",
    "faq.title": "Questions Courantes sur les Services Fiscaux Canadiens",
    "faq.description": "Trouvez des réponses aux questions les plus courantes sur la déclaration fiscale, la conformité et le travail avec un fiscaliste au Canada.",
    "faq.stillHaveTitle": "Vous Avez Encore des Questions?",
    "faq.stillHaveDesc": "N'hésitez pas à nous contacter. Je suis là pour clarifier tout aspect de vos obligations fiscales canadiennes.",
    "faq.contactLink": "Contactez-moi aujourd'hui",
    
    // Contact
    "contact.section": "Contactez-Nous",
    "contact.title": "Prêt à Commencer?",
    "contact.description": "Contactez-moi aujourd'hui pour une consultation gratuite. Je suis là pour répondre à vos questions et vous aider à naviguer vos obligations fiscales canadiennes en toute confiance.",
    "contact.infoTitle": "Informations de Contact",
    "contact.locationLabel": "Emplacement",
    "contact.hoursLabel": "Heures",
    "contact.locationValue": "Service aux clients partout au Canada",
    "contact.hoursValue": "Lun-Ven: 9h-18h HNE",
    "contact.taxSeasonTitle": "Heures de la Saison des Impôts",
    "contact.taxSeasonDesc": "Pendant la saison des impôts (février - avril), des heures prolongées sont disponibles, y compris les soirs et week-ends sur rendez-vous.",
    "contact.virtualDesc": "Consultations virtuelles disponibles pour les clients de toutes les provinces et territoires canadiens.",
    "contact.formTitle": "Envoyez-Moi un Message",
    "contact.nameLabel": "Nom Complet",
    "contact.emailLabel": "Adresse Email",
    "contact.phoneLabel": "Numéro de Téléphone",
    "contact.subjectLabel": "Sujet",
    "contact.messageLabel": "Message",
    "contact.namePlaceholder": "Jean Dupont",
    "contact.emailPlaceholder": "jean@exemple.com",
    "contact.phonePlaceholder": "(555) 123-4567",
    "contact.subjectPlaceholder": "Déclaration T1 d'Impôt Personnel",
    "contact.messagePlaceholder": "Veuillez décrire votre situation fiscale et comment je peux vous aider...",
    "contact.privacyTitle": "Avis de Confidentialité:",
    "contact.privacyText": "Vos informations sont gardées strictement confidentielles et ne seront utilisées que pour répondre à votre demande.",
    "contact.consentText": "En soumettant ce formulaire, vous acceptez d'être contacté concernant votre demande de service fiscal.",
    "contact.submitButton": "Envoyer le Message",
    "contact.scheduleTitle": "Planifier une Consultation Gratuite",
    "contact.scheduleDesc": "Réservez un moment convenable pour discuter de vos besoins fiscaux et financiers.",
    
    // Scheduling
    "scheduling.section": "Prendre Rendez-Vous",
    "scheduling.title": "Planifiez Votre Consultation Gratuite",
    "scheduling.description": "Sélectionnez une date et une heure qui vous conviennent le mieux. Je confirmerai votre rendez-vous dans les 24 heures.",
    "scheduling.selectDate": "Sélectionner une Date",
    "scheduling.selectTime": "Sélectionner une Heure",
    "scheduling.noTimesAvailable": "Aucune heure disponible pour cette date",
    "scheduling.bookingDetails": "Détails de la Réservation",
    "scheduling.selectedDate": "Date Sélectionnée",
    "scheduling.selectedTime": "Heure Sélectionnée",
    "scheduling.fullName": "Nom Complet",
    "scheduling.email": "Adresse Email",
    "scheduling.phone": "Numéro de Téléphone",
    "scheduling.serviceType": "Type de Service",
    "scheduling.selectService": "Sélectionner un service",
    "scheduling.servicePersonal": "Déclaration T1 d'Impôt Personnel",
    "scheduling.serviceNewcomer": "Services Fiscaux pour Nouveaux Arrivants",
    "scheduling.serviceSmallBusiness": "Déclaration de Petite Entreprise",
    "scheduling.serviceCompliance": "Conformité et Révision Fiscale",
    "scheduling.servicePlanning": "Planification et Conseils Fiscaux",
    "scheduling.serviceRepresentation": "Représentation Auprès de l'ARC",
    "scheduling.additionalNotes": "Notes Supplémentaires (Optionnel)",
    "scheduling.notesPlaceholder": "Veuillez partager toute question ou préoccupation spécifique...",
    "scheduling.confirmBooking": "Confirmer la Réservation",
    "scheduling.morning": "Matin",
    "scheduling.afternoon": "Après-midi",
    "scheduling.evening": "Soir",
    "scheduling.virtualMeeting": "Ce sera une consultation virtuelle par appel vidéo.",
    "scheduling.bookingSuccess": "Demande de réservation soumise! Vous recevrez un email de confirmation sous peu.",
    
    // Client Portal
    "clientPortal.title": "Portail Client",
    "clientPortal.subtitle": "Gérez vos documents fiscaux en toute sécurité",
    "clientPortal.login": "Connexion Client",
    "clientPortal.signup": "Créer un Compte",
    "clientPortal.email": "Email",
    "clientPortal.password": "Mot de Passe",
    "clientPortal.name": "Nom Complet",
    "clientPortal.signInButton": "Se Connecter",
    "clientPortal.signUpButton": "Créer un Compte",
    "clientPortal.alreadyHaveAccount": "Vous avez déjà un compte?",
    "clientPortal.noAccount": "Vous n'avez pas de compte?",
    "clientPortal.signInHere": "Connectez-vous ici",
    "clientPortal.signUpHere": "Inscrivez-vous ici",
    "clientPortal.welcomeBack": "Bon retour",
    "clientPortal.logout": "Déconnexion",
    "clientPortal.uploadDocuments": "Télécharger des Documents",
    "clientPortal.myDocuments": "Mes Documents",
    "clientPortal.noDocuments": "Aucun document téléchargé pour le moment",
    "clientPortal.uploadNew": "Télécharger un Nouveau Document",
    "clientPortal.selectCategory": "Sélectionner la Catégorie de Document",
    "clientPortal.description": "Description (optionnel)",
    "clientPortal.chooseFile": "Choisir un Fichier",
    "clientPortal.uploadButton": "Télécharger le Document",
    "clientPortal.uploading": "Téléchargement...",
    "clientPortal.cancel": "Annuler",
    "clientPortal.delete": "Supprimer",
    "clientPortal.uploadedOn": "Téléchargé le",
    "clientPortal.fileSize": "Taille",
    "clientPortal.category": "Catégorie",
    "clientPortal.forgotPassword": "Mot de passe oublié?",
    
    // Forgot Password
    "forgotPassword.title": "Réinitialiser le Mot de Passe",
    "forgotPassword.subtitle": "Entrez votre email et nous vous enverrons un lien pour réinitialiser votre mot de passe",
    "forgotPassword.emailHint": "Nous enverrons un lien de réinitialisation à cette adresse email",
    "forgotPassword.sendButton": "Envoyer le Lien de Réinitialisation",
    "forgotPassword.successTitle": "Vérifiez Votre Email",
    "forgotPassword.successMessage": "Nous avons envoyé un lien de réinitialisation à votre adresse email. Cliquez sur le lien dans l'email pour réinitialiser votre mot de passe.",
    "forgotPassword.checkSpam": "Si vous ne voyez pas l'email, vérifiez votre dossier spam.",
    "forgotPassword.backToLogin": "Retour à la connexion",
    
    // Reset Password
    "resetPassword.title": "Créer un Nouveau Mot de Passe",
    "resetPassword.subtitle": "Entrez votre nouveau mot de passe ci-dessous",
    "resetPassword.newPassword": "Nouveau Mot de Passe",
    "resetPassword.confirmPassword": "Confirmer le Mot de Passe",
    "resetPassword.passwordHint": "Doit comporter au moins 6 caractères",
    "resetPassword.updateButton": "Mettre à Jour le Mot de Passe",
    
    // Document Categories
    "docCategory.t4": "T4 - Revenu d'Emploi",
    "docCategory.t4e": "T4E - Assurance-Emploi",
    "docCategory.t4a": "T4A - Pension, Retraite, Bourses",
    "docCategory.t5": "T5 - Revenu de Placements",
    "docCategory.t5008": "T5008 - Transactions de Titres",
    "docCategory.rl1": "RL-1 - Revenu d'Emploi Québec",
    "docCategory.rl2": "RL-2 - Revenu de Retraite Québec",
    "docCategory.rental": "Revenu de Location",
    "docCategory.selfEmployed": "Travail Autonome / Freelance",
    "docCategory.foreign": "Revenu Étranger",
    "docCategory.medical": "Frais Médicaux",
    "docCategory.education": "Éducation (T2202/RL-8)",
    "docCategory.homeOffice": "Frais de Bureau à Domicile (T2200)",
    "docCategory.rrsp": "Cotisations REER",
    "docCategory.charity": "Dons de Charité",
    "docCategory.childcare": "Frais de Garde d'Enfants",
    "docCategory.property": "Taxe Foncière",
    "docCategory.other": "Autres Documents",

    // Messages
    "messages.title": "Messages",
    "messages.noMessages": "Aucun message pour le moment",
    "messages.writeMessage": "Écrire un message...",
    "messages.send": "Envoyer",
    "messages.you": "Vous",
    "messages.admin": "Conseiller Fiscal",
    "messages.today": "Aujourd'hui",
    "messages.yesterday": "Hier",
    "messages.sending": "Envoi...",
    "messages.loadMore": "Charger plus de messages",

    // Onboarding
    "onboarding.title": "Complétez Votre Profil",
    "onboarding.subtitle": "Configurons votre compte",
    "onboarding.step": "Étape",
    "onboarding.of": "de",
    "onboarding.step1Title": "Informations de Base",
    "onboarding.step1Desc": "Parlez-nous de vous",
    "onboarding.step2Title": "Type de Service",
    "onboarding.step2Desc": "De quel service avez-vous besoin?",
    "onboarding.step3Title": "Détails de la Déclaration Fiscale",
    "onboarding.step3Desc": "Informations supplémentaires pour votre déclaration fiscale",
    "onboarding.fullName": "Nom Complet",
    "onboarding.fullNamePlaceholder": "Jean Dupont",
    "onboarding.phone": "Numéro de Téléphone",
    "onboarding.email": "Email",
    "onboarding.address": "Adresse",
    "onboarding.addressPlaceholder": "123 Rue Principale",
    "onboarding.city": "Ville",
    "onboarding.cityPlaceholder": "Toronto",
    "onboarding.province": "Province",
    "onboarding.selectProvince": "Sélectionner la province",
    "onboarding.postalCode": "Code Postal",
    "onboarding.serviceCategory": "De quel service avez-vous besoin?",
    "onboarding.personal": "Impôt Personnel",
    "onboarding.personalDesc": "Déclarations T1 d'impôt personnel pour particuliers et nouveaux arrivants",
    "onboarding.smallBusiness": "Petite Entreprise",
    "onboarding.smallBusinessDesc": "Déclarations fiscales d'entreprise, déclarations TPS/TVH et planification",
    "onboarding.bookkeeping": "Comptabilité",
    "onboarding.bookkeepingDesc": "Comptabilité mensuelle, suivi des dépenses et dossiers financiers",
    "onboarding.financialReports": "Rapports Financiers et Gestion",
    "onboarding.financialReportsDesc": "Rapports de gestion, analyse financière et services de contrôleur",
    "onboarding.personalInfo": "Informations Personnelles",
    "onboarding.dateOfBirth": "Date de Naissance",
    "onboarding.sin": "Numéro d'Assurance Sociale (NAS)",
    "onboarding.statusInfo": "Informations de Statut",
    "onboarding.maritalStatus": "État Civil",
    "onboarding.selectMaritalStatus": "Sélectionner le statut",
    "onboarding.single": "Célibataire",
    "onboarding.married": "Marié(e)",
    "onboarding.commonLaw": "Union de Fait",
    "onboarding.divorced": "Divorcé(e)",
    "onboarding.widowed": "Veuf/Veuve",
    "onboarding.numberOfDependents": "Nombre de Personnes à Charge",
    "onboarding.firstTimeInCanada": "Première déclaration au Canada?",
    "onboarding.selectYesNo": "Sélectionner oui ou non",
    "onboarding.yes": "Oui",
    "onboarding.no": "Non",
    "onboarding.residencyStatus": "Statut de Résidence",
    "onboarding.selectResidencyStatus": "Sélectionner le statut",
    "onboarding.resident": "Résident",
    "onboarding.nonResident": "Non-résident",
    "onboarding.deemedResident": "Résident Réputé",
    "onboarding.incomeInfo": "Emploi et Revenu",
    "onboarding.incomeType": "Type de Revenu",
    "onboarding.selectIncomeType": "Sélectionner le type",
    "onboarding.employment": "Emploi",
    "onboarding.selfEmployed": "Travailleur Autonome",
    "onboarding.both": "Les Deux",
    "onboarding.other": "Autre",
    "onboarding.workProvince": "Province de Travail",
    "onboarding.back": "Retour",
    "onboarding.continue": "Continuer",
    "onboarding.complete": "Terminer la Configuration",
    "onboarding.saving": "Enregistrement...",
    "onboarding.saveProgress": "Enregistrer la Progression et Continuer Plus Tard",
    "onboarding.fillAllFields": "Veuillez remplir tous les champs requis",
    "onboarding.selectServiceCategory": "Veuillez sélectionner une catégorie de service",
    "onboarding.profileCompleted": "Profil complété! Bienvenue dans votre tableau de bord.",
    "onboarding.progressSaved": "Progression enregistrée avec succès",
    "onboarding.saveFailed": "Échec de l'enregistrement du profil",
    
    // Onboarding Success
    "onboardingSuccess.title": "Inscription Complète!",
    "onboardingSuccess.subtitle": "Votre profil a été configuré avec succès.",
    "onboardingSuccess.description": "Vous avez maintenant accès à votre portail client.",
    "onboardingSuccess.nextSteps": "Vous pouvez maintenant télécharger des documents, suivre l'avancement de votre service et communiquer directement avec nous via votre portail.",
    "onboardingSuccess.accessPortal": "Accéder au Portail Client",
    "onboardingSuccess.contact": "Besoin d'aide? Contactez-nous à tout moment.",
    
    // Footer
    "footer.description": "Services fiscaux canadiens experts pour particuliers, nouveaux arrivants et petites entreprises. Assurer la conformité et maximiser vos rendements.",
    "footer.quickLinks": "Liens Rapides",
    "footer.services": "Services",
    "footer.contact": "Contact",
    "footer.service1": "Déclarations T1 Personnelles",
    "footer.service2": "Services pour Nouveaux Arrivants",
    "footer.service3": "Déclarations de Petite Entreprise",
    "footer.service4": "Conformité Fiscale",
    "footer.service5": "Représentation Auprès de l'ARC",
    "footer.copyright": "Fiscaliste Canadien. Tous droits réservés.",
    "footer.privacy": "Politique de Confidentialité",
    "footer.terms": "Conditions d'Utilisation",
    "footer.disclaimer": "Ce site web est à des fins informatives. Les conseils fiscaux sont fournis au cas par cas lors des consultations. Tous les services sont conformes aux réglementations de l'Agence du revenu du Canada.",
    
    // Admin Panel
    "admin.panel": "Panneau Admin",
    "admin.welcomeBack": "Bon retour",
    "admin.clientPortal": "Portail Client",
    "admin.signOut": "Déconnexion",
    "admin.adminHub": "Centre Admin",
    "admin.selectModule": "Sélectionnez un module ci-dessous pour commencer",
    
    // Admin Modules
    "admin.clientsTitle": "Tableau de Bord Client",
    "admin.clientsDesc": "Gérer tous les clients, voir les détails, documents et statut de déclaration",
    "admin.bookkeepingTitle": "Tableau de Bord Comptabilité",
    "admin.bookkeepingDesc": "Suivre les dépenses, gérer les factures et gérer la comptabilité quotidienne",
    "admin.financialTitle": "Tableau de Bord Financier",
    "admin.financialDesc": "Voir les KPI, analyses de revenus et rapports financiers complets",
    "admin.generalDashboardTitle": "Tableau de Bord Général",
    "admin.generalDashboardDesc": "Aperçu de toutes les opérations système et accès rapide aux fonctions clés",
    "admin.marketingTitle": "Tableau de Bord Marketing",
    "admin.marketingDesc": "Créer des images marketing professionnelles et gérer les campagnes",
    
    // Customer Dashboard
    "admin.customerDashboard": "Tableau de Bord Client",
    "admin.customersTotal": "clients au total",
    "admin.customer": "client",
    "admin.customers": "clients",
    "admin.viewProfile": "Voir le Profil",
    "admin.pending": "En Attente",
    "admin.active": "Actif",
    "admin.completed": "Complété",
    "admin.searchCustomers": "Rechercher des clients...",
    "admin.filterAll": "Tous",
    "admin.filterPersonal": "Impôt Personnel",
    "admin.filterBusiness": "Petite Entreprise",
    "admin.filterBookkeeping": "Comptabilité",
    "admin.filterReports": "Rapports Financiers",
    "admin.noCustomers": "Aucun client trouvé",
    "admin.backToHub": "Retour au Centre",
    
    // Tax Filing Detail Page
    "taxFiling.overview": "Aperçu",
    "taxFiling.documents": "Documents",
    "taxFiling.messages": "Messages",
    "taxFiling.taxYear": "Année Fiscale",
    "taxFiling.filingType": "Type de Déclaration",
    "taxFiling.status": "Statut",
    "taxFiling.created": "Créé",
    "taxFiling.lastUpdated": "Dernière Mise à Jour",
    "taxFiling.statusPending": "Paiement en Attente",
    "taxFiling.statusDocuments": "Téléchargement de Documents",
    "taxFiling.statusReview": "En Révision",
    "taxFiling.statusReady": "Prêt pour Paiement",
    "taxFiling.statusCompleted": "Complété",
    "taxFiling.paymentTimeline": "Calendrier de Paiement",
    "taxFiling.step1": "Paiement Initial",
    "taxFiling.step1Desc": "Payer un dépôt de 50$ CAD pour commencer",
    "taxFiling.step2": "Télécharger les Documents",
    "taxFiling.step2Desc": "Téléchargez vos documents fiscaux",
    "taxFiling.step3": "Nous Préparons",
    "taxFiling.step3Desc": "Nous calculons et préparons votre déclaration",
    "taxFiling.step4": "Paiement Final",
    "taxFiling.step4Desc": "Payer le solde restant",
    "taxFiling.step5": "Déposé",
    "taxFiling.step5Desc": "Soumis à l'ARC",
    "taxFiling.payInitial": "Payer le Dépôt Initial de 50$",
    "taxFiling.uploadDocuments": "Télécharger les Documents",
    "taxFiling.viewReport": "Voir le Rapport Fiscal",
    "taxFiling.payFinal": "Payer le Solde Final",
    "taxFiling.downloadReceipt": "Télécharger le Reçu",
    "taxFiling.initialPaymentPaid": "Paiement Initial Payé",
    "taxFiling.finalPaymentPaid": "Paiement Final Payé",
    "taxFiling.paidOn": "Payé le",
    "taxFiling.amount": "Montant",
    "taxFiling.refundAmount": "Remboursement Estimé",
    "taxFiling.owingAmount": "Montant Dû à l'ARC",
    "taxFiling.finalPrice": "Prix Final du Service",
    "taxFiling.backToDashboard": "Retour au Tableau de Bord"
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = useCallback((key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t
  }), [language, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
